FROM perl:5.24
RUN cpanm -f Moo MooX::Options Types::Standard namespace::autoclean
RUN cpanm -f Data::Printer Log::Dispatchouli Try::Tiny 
RUN cpanm -f Plack 
COPY . /usr/src/data-latency-gather
WORKDIR /usr/src/data-latency-gather
CMD [ "perl", "plackup", "--port", "9090", "dlg.psgi" ]


