package Data::Latency::Gather;
# ABSTRACT: 

use v5.16;
use Moose;
# use MooseX::ClassAttribute;
use namespace::autoclean;

# VERSION: generated by DZP::OurPkgVersion



__PACKAGE__->meta->make_immutable;

1;
